### ISSUE TITLE
Undeclared Jinja2 dependency

### ISSUE THREAD

**Issue by craigds** [geopython/pycsw#1030]
# Description

pycsw depends on `jinja2` for some reason, and this isn't declared in `requirements.txt`

# Environment

- operating system: mac/linux
- Python version: 3.10
- pycsw version: master (c532be3aba731bfee093620c40f64160c3901f8e)

# Steps to Reproduce

```
>>> from pycsw import server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cdestigter/code/pycsw/pycsw/server.py", line 48, in <module>
    from pycsw.ogc.api.util import yaml_load
  File "/Users/cdestigter/code/pycsw/pycsw/ogc/api/util.py", line 45, in <module>
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by kalxas** [comment]
Jinja is pulled in by https://github.com/geopython/pycsw/blob/master/requirements-standalone.txt

**Comment by craigds** [comment]
hm, confusing; I hadn't considered looking in a nonstandard location for this (and, grepping didn't find it)

I suppose that's fine except that things pycsw actually imports _directly_ should probably be mentioned explicitly there, rather than pulled in as a side-effect of some other dependency

**Comment by craigds** [comment]
changed my PR to pull it in explicitly in `requirements-standalone.txt`. thanks

**Comment by craigds** [comment]
it';s not stale, there's an active mergeable PR. someone with write access just needs to click the button...
