### ISSUE TITLE
MySQL Database Setup fails

### ISSUE THREAD

**Issue by georgr** [geopython/pycsw#224]
The database setup (pycsw-admin.py -c setup_db) on MySQL with InnoDB engine fails with error https://gist.github.com/georgr/9187261 and the records table does not get created. I locally fixed that by changing all String(256) fields in the admin.py file with String(255).

Another error occurs afterwards when the first issue is fixed: https://gist.github.com/georgr/9187297 I locally fixed this one by setting the index parameter of the column Column('links', Text, index=True), to False.

With those two hacks it seems to run with mysql.

**Comment by flathers** [comment]
As I look at versions of admin.py from around the time this issue was made, I can't see where there are any String(256) fields listed there.  They all seem to be Text fields.  I had a related problem to this, however, on RedHat 7 and MySQL with InnoDB:

Running the database setup (./bin/pycsw-admin.py -c setup_db -f default.cfg) produced the error "BLOB/TEXT column 'identifier' used in key specification without a key length".  I added String to the imports from sqlalchemy and changed all Text fields that were primary keys or indexed to String(length=255) and this resolved the error.

I don't have enough experience with pycsw to know whether or not changing these datatypes will have any side effects or consequences down the road.

**Comment by stopopol** [comment]
@flathers I can confirm that this solves the reported problem

**Comment by ricardogsilva** [comment]
@stopopol @flathers 

Thanks for your investigation. Improving our test coverage on MySQL is something we have to work on, as it usually does not receive the same amount of love as postgresql and sqlite.

Hopefully with #534 we'll be able to streamline the process of setting up some test instances and improve the situation. 

I'm leaving this open for now, but will revisit later, when the time comes.

Unless you want to submit a PR with the proposed changes?

**Comment by stopopol** [comment]
I can add another comment. I was able to create the tables and import metadata records. However, when accessing http://localhost/pycsw/ I now get this.

<ows:Exception exceptionCode="MissingParameterValue" locator="service">
<ows:ExceptionText>Missing keyword: service</ows:ExceptionText>
</ows:Exception>

I don't know what the problem might be though. I compared the tables in mysql with another installation on postgres and they look fine.

**Comment by stopopol** [comment]
OK. This might be a follow-up bug.
I was able to load records into the mysql database, but when a geonetwork instance tries to harvest it, this error message is thrown:

2017-09-13 10:52:57,465 ERROR [deims_csw] - Unknown error trying to harvest
2017-09-13 10:52:57,465 ERROR [deims_csw] - Raised exception when searching: Record serialization failed: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
2017-09-13 10:52:57,465 ERROR [deims_csw] - Raised exception when searching: Record serialization failed: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
OperationAbortedEx : Raised exception when searching: Record serialization failed: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.doSearch(Harvester.java:608)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.search(Harvester.java:276)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.harvest(Harvester.java:142)
	at org.fao.geonet.kernel.harvest.harvester.csw.CswHarvester.doHarvest(CswHarvester.java:178)
	at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester$HarvestWithIndexProcessor.process(AbstractHarvester.java:649)
	at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester.harvest(AbstractHarvester.java:721)
	at org.fao.geonet.kernel.harvest.harvester.HarvesterJob.execute(HarvesterJob.java:51)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.fao.geonet.csw.common.exceptions.NoApplicableCodeEx: code=NoApplicableCode, locator=service, message=Record serialization failed: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
	at org.fao.geonet.csw.common.exceptions.CatalogException.createException(CatalogException.java:159)
	at org.fao.geonet.csw.common.exceptions.CatalogException.unmarshal(CatalogException.java:124)
	at org.fao.geonet.csw.common.requests.CatalogRequest.execute(CatalogRequest.java:185)
	at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.doSearch(Harvester.java:593)
	... 8 more
