### ISSUE TITLE
Python 3 issue with pycsw.admin

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/pycsw#490]
In a python 3 environment with pycsw 2, when I do:
```
pycsw-admin.py -c export_records -f default.cfg -p /export
```
I get: 
```
Exporting records

Processing USGS_BBLEH_SANDY_076
Writing to file /export/USGS_BBLEH_SANDY_076.xml
Traceback (most recent call last):
  File "/opt/pycsw/pycsw/core/admin.py", line 396, in export_records
    xml.write(record.xml)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/pycsw-admin.py", line 266, in <module>
    admin.export_records(CONTEXT, DATABASE, TABLE, XML_DIRPATH)
  File "/opt/pycsw/pycsw/core/admin.py", line 398, in export_records
    raise RuntimeError("Error writing to %s" % filename, err)
RuntimeError: ('Error writing to /export/USGS_BBLEH_SANDY_076.xml', TypeError('write() argument must be str, not bytes',))
```
if I change [this line in admin.py](https://github.com/geopython/pycsw/blob/master/pycsw/core/admin.py#L394) from
```
 with open(filename, 'w') as xml:
```
to
```
 with open(filename, 'wb') as xml:
```
then I get the following error:

```
Querying database sqlite:////database/cite.db, table records ....
Found 30 records

Exporting records

Processing gov.usgs.cmg:USGS_BBLEH_SANDY_076
 Sanitizing identifier
Writing to file /export/USGS_BBLEH_SANDY_076.xml
Traceback (most recent call last):
  File "/opt/pycsw/pycsw/core/admin.py", line 395, in export_records
    xml.write('<?xml version="1.0" encoding="UTF-8"?>\n')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/pycsw-admin.py", line 266, in <module>
    admin.export_records(CONTEXT, DATABASE, TABLE, XML_DIRPATH)
  File "/opt/pycsw/pycsw/core/admin.py", line 398, in export_records
    raise RuntimeError("Error writing to %s" % filename, err)
RuntimeError: ('Error writing to /export/USGS_BBLEH_SANDY_076.xml', TypeError("a bytes-like object is required, not 'str'",))
```

**Comment by kwilcox** [comment]
@tomkralidis ive had a fix for this that I forgot to PR... will send soon.

**Comment by kwilcox** [comment]
I'm stuck getting the py3 tests to pass locally. @tomkralidis have you seen this before?

`paver test -s manager`

```
Exception: the document is not valid.
Error: Element '{http://www.opengis.net/cat/csw/2.0.2}Transaction', attribute 'service': The value '(null)' does not match the fixed value constraint 'CSW'.
```

```
URL:http://localhost:8000?config=tests/suites/manager/default.cfg
REQUEST:<?xml version="1.0" encoding="UTF-8"?>
<csw:Transaction xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ogc="http://www.opengis.net/ogc" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-publication.xsd" service="CSW" version="2.0.2">
  <csw:Delete>
    <csw:Constraint version="1.1.0">
      <ogc:Filter>
        <ogc:PropertyIsLike wildCard="%" singleChar="." escapeChar="\">
          <ogc:PropertyName>dc:identifier</ogc:PropertyName>
          <ogc:Literal>%</ogc:Literal>
        </ogc:PropertyIsLike>
      </ogc:Filter>
    </csw:Constraint>
  </csw:Delete>
</csw:Transaction>
```

**Comment by tomkralidis** [comment]
@kwilcox it's probably the libxml2 issue: #454.

**Comment by kwilcox** [comment]
Ugh. that was it.
