### ISSUE TITLE
fix CSW-T GM03 Insert errors

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#506]
# Description
Running CSW-T Insert operations against GM03 metadata results in parsing errors.
# Environment

- operating system: Debian
- Python version: 2.7
- pycsw version: master
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

```pycon
>>> from owslib.csw import CatalogueServiceWeb
>>> csw = CatalogueServiceWeb('http://localhost:8000/')
>>> csw.transaction(ttype='insert', typename='gm03:TRANSFER', record=open('/tmp/OWSLib/OWSLib/tests/resources/gm03_example1.xml').read())
Traceback (most recent call last):
  File "ee.py", line 3, in <module>
    csw.transaction(ttype='insert', typename='gm03:TRANSFER', record=open('/home/tkralidi/work/foss4g/OWSLib/OWSLib/tests/resources/gm03_example1.xml').read())
  File "/home/tkralidi/work/foss4g/pycsw/master/local/lib/python2.7/site-packages/owslib/csw.py", line 455, in transaction
    self._invoke()
  File "/home/tkralidi/work/foss4g/pycsw/master/local/lib/python2.7/site-packages/owslib/csw.py", line 694, in _invoke
    raise ows.ExceptionReport(self._exml, self.owscommon.namespace)
owslib.ows.ExceptionReport: "Transaction (insert) failed: record parsing failed: 'list' object has no attribute 'date'"

```
# Additional Information

**Comment by tomkralidis** [comment]
Fixed in master and 2.0 branch.
