### ISSUE TITLE
Problem to create my first pycsw server: sqlalchemy.exc.NoSuchTableError: records

### ISSUE THREAD

**Issue by rmmariano** [geopython/pycsw#590]
# Description

I'm trying to test the pycsw to use it to serve the metadata of my project, but I'm not able to test it.

I would like to create a table in Postgres database and serve this table (metadata) through CSW in XML using the ISO 19115. Is it possible?

I followed the steps described in the following link, but no success. http://docs.pycsw.org/en/stable/installation.html#for-developers-and-the-truly-impatient

The first error occurred because I didn't have the table 'pycsw' in my Postgres database. 
So I created it, but the error changed. I've tried to create the table 'records', but it did not help me. Now the error is the following:

Command: http://localhost:8000/?service=CSW&version=2.0.2&request=GetCapabilities

```
/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Could not load repository (local): records
Traceback (most recent call last):
  File "/home/rodrigo/personal/files/docs/emprego/datainfo/ws/other/geopython/pycsw/pycsw/server.py", line 406, in dispatch
    repo_filter
  File "/home/rodrigo/personal/files/docs/emprego/datainfo/ws/other/geopython/pycsw/pycsw/core/repository.py", line 122, in __init__
    "schema": schema_name or None,
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py", line 75, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 130, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 158, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 186, in __init__
    self._setup_table()
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 532, in _setup_table
    **table_kw
  File "<string>", line 2, in __new__
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/util/deprecations.py", line 130, in warned
    return fn(*args, **kwargs)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 496, in __new__
    metadata._remove_table(name, schema)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 491, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 585, in _init
    resolve_fks=resolve_fks,
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 626, in _autoload
    _extend_on=_extend_on,
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2147, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1604, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 431, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/reflection.py", line 646, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: records
basic service options error: NoApplicableCode, service, Could not initialize repository. Check server logs
127.0.0.1 - - [26/Mar/2019 19:51:25] "GET /?service=CSW&version=2.0.2&request=GetCapabilities HTTP/1.1" 200 381
Could not load repository (local): records
Traceback (most recent call last):
  File "/home/rodrigo/personal/files/docs/emprego/datainfo/ws/other/geopython/pycsw/pycsw/server.py", line 406, in dispatch
    repo_filter
  File "/home/rodrigo/personal/files/docs/emprego/datainfo/ws/other/geopython/pycsw/pycsw/core/repository.py", line 122, in __init__
    "schema": schema_name or None,
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py", line 75, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 130, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 158, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 186, in __init__
    self._setup_table()
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/ext/declarative/base.py", line 532, in _setup_table
    **table_kw
  File "<string>", line 2, in __new__
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/util/deprecations.py", line 130, in warned
    return fn(*args, **kwargs)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 496, in __new__
    metadata._remove_table(name, schema)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 491, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 585, in _init
    resolve_fks=resolve_fks,
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 626, in _autoload
    _extend_on=_extend_on,
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2147, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1604, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 431, in reflecttable
    table, include_columns, exclude_columns, resolve_fks, **opts
  File "/home/rodrigo/.virtualenvs/pycsw/lib/python3.5/site-packages/sqlalchemy/engine/reflection.py", line 646, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: records
basic service options error: NoApplicableCode, service, Could not initialize repository. Check server logs
127.0.0.1 - - [26/Mar/2019 19:51:25] "GET /favicon.ico HTTP/1.1" 400 386
```

# Environment

```
pycsw-admin.py -c get_sysprof

pycsw system profile
    --------------------
    Python version: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
    os: linux
    SQLAlchemy: 1.3.1
    Shapely: 1.6.4.post2
    lxml: 4.3.2
    libxml2: (2, 9, 9)
    pyproj: 2.1.2
    OWSLib: 0.17.1
Done
```

- operating system: Ubuntu
- Python version: 3.5
- pycsw version: latest
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

- Create the 'pycsw' database in Postgres
- Create the table 'records' in the database above
- Follow the steps in: http://docs.pycsw.org/en/stable/installation.html#for-developers-and-the-truly-impatient

Could someone help me? 

Thank you in advance.

**Comment by tomkralidis** [comment]
@rmmariano the quick install assumes using the sample SQLite database that is shipped with pycsw proper.  For PostgreSQL/PostGIS can you try the steps at http://docs.pycsw.org/en/stable/administration.html#metadata-repository-setup ?

Note that you can use the [pycsw-devel](https://lists.osgeo.org/mailman/listinfo/pycsw-devel) mailing list for questions.

**Comment by rmmariano** [comment]
@tomkralidis thank you for the information. I was not able to fix my problem with your link, but I'm going to send an e-mail in your list.

**Comment by tomkralidis** [comment]
Thanks @rmmariano.  Continued on http://osgeo-org.1560.x6.nabble.com/Install-and-execute-pycsw-with-a-PostgreSQL-with-PostGIS-td5400021.html
