### ISSUE TITLE
Docs fail to build with sphinx 2.4

### ISSUE THREAD

**Issue by sebastic** [geopython/pycsw#609]
# Description

As reported by Andreas Beckmann in [Debian Bug #959775](https://bugs.debian.org):
> pycsw started to FTBFS when sphinx 2.4 reached sid:
> ```
> [...]
> PYTHONPATH=. http_proxy='127.0.0.1:9' sphinx-build -N -bhtml docs/ build/html # HTML generator
> Running Sphinx v2.4.3
> making output directory... done
> building [mo]: targets for 0 po files that are out of date
> building [html]: targets for 31 source files that are out of date
> updating environment: [new config] 31 added, 0 changed, 0 removed
> reading sources... [  3%] administration
> reading sources... [  6%] api
> reading sources... [  9%] ckan
> reading sources... [ 12%] committers
> reading sources... [ 16%] configuration
> reading sources... [ 19%] contributing
> reading sources... [ 22%] csw-support
> reading sources... [ 25%] distributedsearching
> reading sources... [ 29%] docker
> reading sources... [ 32%] geonode
> reading sources... [ 35%] hhypermap
> reading sources... [ 38%] index
> reading sources... [ 41%] installation
> reading sources... [ 45%] introduction
> reading sources... [ 48%] json
> reading sources... [ 51%] license
> reading sources... [ 54%] migration-guide
> reading sources... [ 58%] oaipmh
> reading sources... [ 61%] odc
> reading sources... [ 64%] opensearch
> reading sources... [ 67%] outputschemas
> reading sources... [ 70%] profiles
> reading sources... [ 74%] repofilters
> reading sources... [ 77%] repositories
> reading sources... [ 80%] sitemaps
> reading sources... [ 83%] soap
> reading sources... [ 87%] sru
> reading sources... [ 90%] support
> reading sources... [ 93%] testing
> reading sources... [ 96%] tools
> reading sources... [100%] transactions
>
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... done
> preparing documents... done
> writing output... [  3%] administration
>
> Theme error:
> An error happened in rendering the page administration.
> Reason: TemplateNotFound('i')
> ```
> [pycsw_2.4.2+dfsg-2.log.gz](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=959775;filename=pycsw_2.4.2%2Bdfsg-2.log.gz;msg=5)

# Environment

- operating system: Debian GNU/Linux
- Python version: 3.8.3~rc1
- pycsw version: 2.4.2
- source/distribution
  - [x] DebianGIS/UbuntuGIS

# Steps to Reproduce

Build docs with python3-sphinx from Debian unstable.

# Additional Information

Traceback:
```
# PYTHONPATH=. http_proxy='127.0.0.1:9' sphinx-build -v -T -N -bhtml docs/ build/html # HTML generator
Running Sphinx v2.4.3
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 31 source files that are out of date
updating environment: [new config] 31 added, 0 changed, 0 removed
reading sources... [  3%] administration
reading sources... [  6%] api
reading sources... [  9%] ckan
reading sources... [ 12%] committers
reading sources... [ 16%] configuration
reading sources... [ 19%] contributing
reading sources... [ 22%] csw-support
reading sources... [ 25%] distributedsearching
reading sources... [ 29%] docker
reading sources... [ 32%] geonode
reading sources... [ 35%] hhypermap
reading sources... [ 38%] index
reading sources... [ 41%] installation
reading sources... [ 45%] introduction
reading sources... [ 48%] json
reading sources... [ 51%] license
reading sources... [ 54%] migration-guide
reading sources... [ 58%] oaipmh
reading sources... [ 61%] odc
reading sources... [ 64%] opensearch
reading sources... [ 67%] outputschemas
reading sources... [ 70%] profiles
reading sources... [ 74%] repofilters
reading sources... [ 77%] repositories
reading sources... [ 80%] sitemaps
reading sources... [ 83%] soap
reading sources... [ 87%] sru
reading sources... [ 90%] support
reading sources... [ 93%] testing
reading sources... [ 96%] tools
reading sources... [100%] transactions

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  3%] administration

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 1023, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 192, in render
    return self.environment.get_template(template).render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/share/sphinx/themes/basic/page.html", line 9, in top-level template code
    #}
  File "/build/pycsw-2.4.2+dfsg/docs/_templates/layout.html", line 1, in top-level template code
    {% extends "!layout.html" %}
  File "/usr/share/sphinx/themes/classic/layout.html", line 9, in top-level template code
    #}
  File "/usr/share/sphinx/themes/classic/../basic/layout.html", line 56, in top-level template code
    <p class="logo"><a href="{{ pathto(master_doc) }}">
  File "/usr/share/sphinx/themes/classic/../basic/layout.html", line 65, in block "content"
    {%- endfor %}
  File "/usr/share/sphinx/themes/classic/../basic/layout.html", line 65, in block "sidebar2"
    {%- endfor %}
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 465, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "/usr/share/sphinx/themes/classic/../basic/layout.html", line 29, in template
    {%- macro relbar() %}
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 213, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: i

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 618, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 1030, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page administration.
Reason: TemplateNotFound('i')

Theme error:
An error happened in rendering the page administration.
Reason: TemplateNotFound('i')
```

**Comment by tomkralidis** [comment]
Thanks @sebastic .  Fixed in master and 2.4 branch.
