### ISSUE TITLE
New API - BBOX Query doesn't return expected records

### ISSUE THREAD

**Issue by epifanio** [geopython/pycsw#712]
# Description
New API - BBOX Query doesn't return expected records.

using CSW url syntax below:
```
https://sios.csw.met.no/csw?service=CSW&version=2.0.2&request=GetRecords&ElementSetName=full&typenames=csw:Record&resulttype=results&bbox=0,0,180,90
```
I can extract records from the selected bbox region, the same query using the new API:

```
https://sios.csw.met.no/collections/metadata:main/items?bbox=0%200%20180%2090&limit=10&f=json
```

Doesn't return any record,

# Environment

- operating system:
Ubutnu 21.04
- Python version:
3.9
- pycsw version:
git master
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [x] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
This returns expected records:

```
https://sios.csw.met.no/csw?service=CSW&version=2.0.2&request=GetRecords&ElementSetName=full&typenames=csw:Record&resulttype=results&bbox=0,0,180,90
```

The same using API doesn't return records:

```
https://sios.csw.met.no/collections/metadata:main/items?bbox=0%200%20180%2090&limit=10&f=json
```

# Additional Information

**Comment by tomkralidis** [comment]
@epifanio the bbox parameter needs to be comma-separated:

https://sios.csw.met.no/collections/metadata:main/items?bbox=0,0,180,90&limit=10&f=json

However this results in a 500.  Can you provide a traceback?

**Comment by epifanio** [comment]
On the docker logs, the request is received:

```
sios_pycsw.1.jqxszhnp9n2u@csw.met.no    | 10.0.1.9 - - [12/Oct/2021:00:55:28 +0000] "GET /collections/metadata:main/items?bbox=0,0,180,90&limit=10&f=json HTTP/1.1" 500 290 "https://github.com/geopython/pycsw/issues/712" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
sios_pycsw.1.jqxszhnp9n2u@csw.met.no    | 10.0.1.9 - - [12/Oct/2021:00:55:28 +0000] "GET /favicon.ico HTTP/1.1" 404 232 "https://sios.csw.met.no/collections/metadata:main/items?bbox=0,0,180,90&limit=10&f=json" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
```

Full log attached below. I see this is suspicious:

```
  File "/home/pycsw/pycsw/pycsw/ogc/api/records.py", line 141, in get_content_type
    if 'text/html' in headers['Accept']:
KeyError: 'Accept'

```

I will make sure I am up-to-date with master.

```
[SQL: SELECT count(*) AS count_1 
FROM (SELECT sios_records.identifier AS sios_records_identifier, sios_records.typename AS sios_records_typename, sios_records.schema AS sios_records_schema, sios_records.mdsource AS sios_records_mdsource, sios_records.insert_date AS sios_records_insert_date, sios_records.xml AS sios_records_xml, sios_records.anytext AS sios_records_anytext, sios_records.metadata AS sios_records_metadata, sios_records.metadata_type AS sios_records_metadata_type, sios_records.language AS sios_records_language, sios_records.type AS sios_records_type, sios_records.title AS sios_records_title, sios_records.title_alternate AS sios_records_title_alternate, sios_records.abstract AS sios_records_abstract, sios_records.keywords AS sios_records_keywords, sios_records.keywordstype AS sios_records_keywordstype, sios_records.parentidentifier AS sios_records_parentidentifier, sios_records.relation AS sios_records_relation, sios_records.time_begin AS sios_records_time_begin, sios_records.time_end AS sios_records_time_end, sios_records.topicategory AS sios_records_topicategory, sios_records.resourcelanguage AS sios_records_resourcelanguage, sios_records.creator AS sios_records_creator, sios_records.publisher AS sios_records_publisher, sios_records.contributor AS sios_records_contributor, sios_records.organization AS sios_records_organization, sios_records.distributor AS sios_records_distributor, sios_records.securityconstraints AS sios_records_securityconstraints, sios_records.accessconstraints AS sios_records_accessconstraints, sios_records.useconstraints AS sios_records_useconstraints, sios_records.otherconstraints AS sios_records_otherconstraints, sios_records.date AS sios_records_date, sios_records.date_revision AS sios_records_date_revision, sios_records.date_creation AS sios_records_date_creation, sios_records.date_publication AS sios_records_date_publication, sios_records.date_modified AS sios_records_date_modified, sios_records.format AS sios_records_format, sios_records.source AS sios_records_source, sios_records.crs AS sios_records_crs, sios_records.geodescode AS sios_records_geodescode, sios_records.denominator AS sios_records_denominator, sios_records.distancevalue AS sios_records_distancevalue, sios_records.distanceuom AS sios_records_distanceuom, sios_records.wkt_geometry AS sios_records_wkt_geometry, sios_records.servicetype AS sios_records_servicetype, sios_records.servicetypeversion AS sios_records_servicetypeversion, sios_records.operation AS sios_records_operation, sios_records.couplingtype AS sios_records_couplingtype, sios_records.operateson AS sios_records_operateson, sios_records.operatesonidentifier AS sios_records_operatesonidentifier, sios_records.operatesoname AS sios_records_operatesoname, sios_records.degree AS sios_records_degree, sios_records.classification AS sios_records_classification, sios_records.conditionapplyingtoaccessanduse AS sios_records_conditionapplyingtoaccessanduse, sios_records.lineage AS sios_records_lineage, sios_records.responsiblepartyrole AS sios_records_responsiblepartyrole, sios_records.specificationtitle AS sios_records_specificationtitle, sios_records.specificationdate AS sios_records_specificationdate, sios_records.specificationdatetype AS sios_records_specificationdatetype, sios_records.platform AS sios_records_platform, sios_records.instrument AS sios_records_instrument, sios_records.sensortype AS sios_records_sensortype, sios_records.cloudcover AS sios_records_cloudcover, sios_records.bands AS sios_records_bands, sios_records.links AS sios_records_links, sios_records.anytext_tsvector AS sios_records_anytext_tsvector 
FROM sios_records 
WHERE query_spatial(records_wkt_geometry, 'POLYGON((0.00 0.00, 0.00 90.00, 180.00 90.00, 180.00 0.00, 0.00 0.00))', 'bbox', 'false') = 'true') AS anon_1]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Mon, 11 Oct 2021 23:45:01] [ERROR] file=/usr/local/lib/python3.8/site-packages/flask/app.py line=1454 module=app function=log_exception Exception on /collections/metadata:main/items [HEAD]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pycsw/pycsw/pycsw/wsgi_flask.py", line 149, in items
    return get_response(api_.items(dict(request.headers), request.args))
  File "/home/pycsw/pycsw/pycsw/ogc/api/records.py", line 401, in items
    headers_['Content-Type'] = self.get_content_type(headers_, args)
  File "/home/pycsw/pycsw/pycsw/ogc/api/records.py", line 141, in get_content_type
    if 'text/html' in headers['Accept']:
KeyError: 'Accept'
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=427 module=records function=items Transforming property filters into CQL
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=446 module=records function=items Evaluating CQL and other specified filtering parameters
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=453 module=records function=items Just other specified filtering parameters detected
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=456 module=records function=items CQL query: BBOX(geometry, 0,0,180,90)
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=460 module=records function=items Parsing CQL into AST
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=462 module=records function=items Abstract syntax tree: <pycql.ast.BBoxPredicateNode object at 0x7fbf35b3d7f0>
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=464 module=records function=items Transforming AST into filters
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=466 module=records function=items Filter: query_spatial(records_wkt_geometry, 'POLYGON((0.00 0.00, 0.00 90.00, 180.00 90.00, 180.00 0.00, 0.00 0.00))', 'bbox', 'false') = 'true'
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=473 module=records function=items limit specified
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=482 module=records function=items Query: SELECT sios_records.identifier AS sios_records_identifier, sios_records.typename AS sios_records_typename, sios_records.schema AS sios_records_schema, sios_records.mdsource AS sios_records_mdsource, sios_records.insert_date AS sios_records_insert_date, sios_records.xml AS sios_records_xml, sios_records.anytext AS sios_records_anytext, sios_records.metadata AS sios_records_metadata, sios_records.metadata_type AS sios_records_metadata_type, sios_records.language AS sios_records_language, sios_records.type AS sios_records_type, sios_records.title AS sios_records_title, sios_records.title_alternate AS sios_records_title_alternate, sios_records.abstract AS sios_records_abstract, sios_records.keywords AS sios_records_keywords, sios_records.keywordstype AS sios_records_keywordstype, sios_records.parentidentifier AS sios_records_parentidentifier, sios_records.relation AS sios_records_relation, sios_records.time_begin AS sios_records_time_begin, sios_records.time_end AS sios_records_time_end, sios_records.topicategory AS sios_records_topicategory, sios_records.resourcelanguage AS sios_records_resourcelanguage, sios_records.creator AS sios_records_creator, sios_records.publisher AS sios_records_publisher, sios_records.contributor AS sios_records_contributor, sios_records.organization AS sios_records_organization, sios_records.distributor AS sios_records_distributor, sios_records.securityconstraints AS sios_records_securityconstraints, sios_records.accessconstraints AS sios_records_accessconstraints, sios_records.useconstraints AS sios_records_useconstraints, sios_records.otherconstraints AS sios_records_otherconstraints, sios_records.date AS sios_records_date, sios_records.date_revision AS sios_records_date_revision, sios_records.date_creation AS sios_records_date_creation, sios_records.date_publication AS sios_records_date_publication, sios_records.date_modified AS sios_records_date_modified, sios_records.format AS sios_records_format, sios_records.source AS sios_records_source, sios_records.crs AS sios_records_crs, sios_records.geodescode AS sios_records_geodescode, sios_records.denominator AS sios_records_denominator, sios_records.distancevalue AS sios_records_distancevalue, sios_records.distanceuom AS sios_records_distanceuom, sios_records.wkt_geometry AS sios_records_wkt_geometry, sios_records.servicetype AS sios_records_servicetype, sios_records.servicetypeversion AS sios_records_servicetypeversion, sios_records.operation AS sios_records_operation, sios_records.couplingtype AS sios_records_couplingtype, sios_records.operateson AS sios_records_operateson, sios_records.operatesonidentifier AS sios_records_operatesonidentifier, sios_records.operatesoname AS sios_records_operatesoname, sios_records.degree AS sios_records_degree, sios_records.classification AS sios_records_classification, sios_records.conditionapplyingtoaccessanduse AS sios_records_conditionapplyingtoaccessanduse, sios_records.lineage AS sios_records_lineage, sios_records.responsiblepartyrole AS sios_records_responsiblepartyrole, sios_records.specificationtitle AS sios_records_specificationtitle, sios_records.specificationdate AS sios_records_specificationdate, sios_records.specificationdatetype AS sios_records_specificationdatetype, sios_records.platform AS sios_records_platform, sios_records.instrument AS sios_records_instrument, sios_records.sensortype AS sios_records_sensortype, sios_records.cloudcover AS sios_records_cloudcover, sios_records.bands AS sios_records_bands, sios_records.links AS sios_records_links, sios_records.anytext_tsvector AS sios_records_anytext_tsvector 
FROM sios_records 
WHERE query_spatial(records_wkt_geometry, 'POLYGON((0.00 0.00, 0.00 90.00, 180.00 90.00, 180.00 0.00, 0.00 0.00))', 'bbox', 'false') = 'true'
Tue, 12 Oct 2021 00:55:28] [DEBUG] file=/home/pycsw/pycsw/pycsw/ogc/api/records.py line=483 module=records function=items Querying repository
Tue, 12 Oct 2021 00:55:28] [ERROR] file=/usr/local/lib/python3.8/site-packages/flask/app.py line=1454 module=app function=log_exception Exception on /collections/metadata:main/items [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "records_wkt_geometry" does not exist
LINE 4: WHERE query_spatial(records_wkt_geometry, 'POLYGON((0.00 0.0...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pycsw/pycsw/pycsw/wsgi_flask.py", line 149, in items
    return get_response(api_.items(dict(request.headers), request.args))
  File "/home/pycsw/pycsw/pycsw/ogc/api/records.py", line 484, in items
    count = query.count()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3078, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2819, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2796, in one
    return self._iter().one()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "records_wkt_geometry" does not exist
LINE 4: WHERE query_spatial(records_wkt_geometry, 'POLYGON((0.00 0.0...
                            ^

[SQL: SELECT count(*) AS count_1 
FROM (SELECT sios_records.identifier AS sios_records_identifier, sios_records.typename AS sios_records_typename, sios_records.schema AS sios_records_schema, sios_records.mdsource AS sios_records_mdsource, sios_records.insert_date AS sios_records_insert_date, sios_records.xml AS sios_records_xml, sios_records.anytext AS sios_records_anytext, sios_records.metadata AS sios_records_metadata, sios_records.metadata_type AS sios_records_metadata_type, sios_records.language AS sios_records_language, sios_records.type AS sios_records_type, sios_records.title AS sios_records_title, sios_records.title_alternate AS sios_records_title_alternate, sios_records.abstract AS sios_records_abstract, sios_records.keywords AS sios_records_keywords, sios_records.keywordstype AS sios_records_keywordstype, sios_records.parentidentifier AS sios_records_parentidentifier, sios_records.relation AS sios_records_relation, sios_records.time_begin AS sios_records_time_begin, sios_records.time_end AS sios_records_time_end, sios_records.topicategory AS sios_records_topicategory, sios_records.resourcelanguage AS sios_records_resourcelanguage, sios_records.creator AS sios_records_creator, sios_records.publisher AS sios_records_publisher, sios_records.contributor AS sios_records_contributor, sios_records.organization AS sios_records_organization, sios_records.distributor AS sios_records_distributor, sios_records.securityconstraints AS sios_records_securityconstraints, sios_records.accessconstraints AS sios_records_accessconstraints, sios_records.useconstraints AS sios_records_useconstraints, sios_records.otherconstraints AS sios_records_otherconstraints, sios_records.date AS sios_records_date, sios_records.date_revision AS sios_records_date_revision, sios_records.date_creation AS sios_records_date_creation, sios_records.date_publication AS sios_records_date_publication, sios_records.date_modified AS sios_records_date_modified, sios_records.format AS sios_records_format, sios_records.source AS sios_records_source, sios_records.crs AS sios_records_crs, sios_records.geodescode AS sios_records_geodescode, sios_records.denominator AS sios_records_denominator, sios_records.distancevalue AS sios_records_distancevalue, sios_records.distanceuom AS sios_records_distanceuom, sios_records.wkt_geometry AS sios_records_wkt_geometry, sios_records.servicetype AS sios_records_servicetype, sios_records.servicetypeversion AS sios_records_servicetypeversion, sios_records.operation AS sios_records_operation, sios_records.couplingtype AS sios_records_couplingtype, sios_records.operateson AS sios_records_operateson, sios_records.operatesonidentifier AS sios_records_operatesonidentifier, sios_records.operatesoname AS sios_records_operatesoname, sios_records.degree AS sios_records_degree, sios_records.classification AS sios_records_classification, sios_records.conditionapplyingtoaccessanduse AS sios_records_conditionapplyingtoaccessanduse, sios_records.lineage AS sios_records_lineage, sios_records.responsiblepartyrole AS sios_records_responsiblepartyrole, sios_records.specificationtitle AS sios_records_specificationtitle, sios_records.specificationdate AS sios_records_specificationdate, sios_records.specificationdatetype AS sios_records_specificationdatetype, sios_records.platform AS sios_records_platform, sios_records.instrument AS sios_records_instrument, sios_records.sensortype AS sios_records_sensortype, sios_records.cloudcover AS sios_records_cloudcover, sios_records.bands AS sios_records_bands, sios_records.links AS sios_records_links, sios_records.anytext_tsvector AS sios_records_anytext_tsvector 
FROM sios_records 
WHERE query_spatial(records_wkt_geometry, 'POLYGON((0.00 0.00, 0.00 90.00, 180.00 90.00, 180.00 0.00, 0.00 0.00))', 'bbox', 'false') = 'true') AS anon_1]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Comment by tomkralidis** [comment]
@epifanio are you able to provide the full traceback for the life of the request?  It looks like PostgreSQL/PostGIS is not getting picked up as the DB backend.

**Comment by tomkralidis** [comment]
@epifanio testing further, I'm unable to reproduce.  You need to ensure your DB is setup with the PostGIS extensions accordingly.

**Comment by epifanio** [comment]
@tomkralidis probably I need to re-create the DB, I was using an existing one - which is already in use with pycsw -  it is a postgis DB running under docker. 

I am using the same machine used in the compose environment from the pycsw docker settings - 

```
  postgis:
    image: postgis/postgis:12-3.0-alpine
```

I see be the  API call refer to a "missing function" wrapped into a custom SQL method in admin.py 

[```.. /pycsw/core/admin.py:239: function_query_spatial = '''```` ](https://github.com/geopython/pycsw/blob/master/pycsw/core/admin.py#L225-L283)

Somehow this code has not been executed ?!
