### ISSUE TITLE
Allow using a DB view for the repository table

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pycsw#747]
I'm trying to use a postgresql materialized view as my repository table. Unfortunately it fails with the following error:

```python
Could not load repository (local): Mapper mapped class dataset->emc_pycsw_view could not assemble any primary key columns for mapped table 'emc_pycsw_view'
Traceback (most recent call last):
  File "/home/pycsw/pycsw/pycsw/server.py", line 410, in dispatch
    self.repository = repository.Repository(
  File "/home/pycsw/pycsw/pycsw/core/repository.py", line 114, in __init__
    self.dataset = type(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 72, in __init__
    _as_declarative(reg, cls, dict_)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 177, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 314, in __init__
    self._early_mapping(mapper_kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 200, in _early_mapping
    self.map(mapper_kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 992, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 685, in __init__
    self._configure_pks()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1327, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper mapped class dataset->emc_pycsw_view could not assemble any primary key columns for mapped table 'emc_pycsw_view'
basic service options error: NoApplicableCode, service, Could not initialize repository. Check server logs
```

It seems sqlalchemy would like there to be a primary key in the mapped table, but postgres does not really support putting primary keys on views. I tried creating a `UNIQUE` index on the view, but that does not change the error though. 

The [sqlalchemy docs on reflecting views](https://docs.sqlalchemy.org/en/14/core/reflection.html#reflecting-views) mention that it is possible to provide information on primary keys by overriding the table definition with a primary key declaration.

It would be nice to be able to leverage this in order to allow pycsw to work with a view as its records table.

### Possible implementation

I'm thinking about a mechanism that would apply to custom mappings. 

When there are custom mappings to be loaded, the loaded `mappings.MD_CORE_MODEL` dict could be allowed to have an additional `sqlalchemy_table_mapping_kwargs` dict, which would be used to complete the `__table_args__` keyword arg that is used [when initializing the pycsw repository](https://github.com/geopython/pycsw/blob/04c7f59f8a3bfa73b77f1e32ad3c55519b92563f/pycsw/core/repository.py#L114)

Not sure it works, as I've not tried it yet, but I'd be willing to work on this and submit a PR. @tomkralidis Is this something you'd consider to add to pycsw?

### Steps to Reproduce

1. Create a materialized view
2. Cutomize pycsw's config in order to use said view as the repository table
3. Launch pycsw
4. Perform any request

**Comment by tomkralidis** [comment]
Makes sense @ricardogsilva.  How would this be realized from the user perspective?  i.e. extending pycsw `repository` configuration, or would this be for downstream applications?

**Comment by jmckenna** [comment]
@ricardogsilva I am interested in your CKAN->CSW workaround, wow, that sounds extremely useful.
