### ISSUE TITLE
FES validation issue with CSW 3.0

### ISSUE THREAD

**Issue by kalxas** [geopython/pycsw#796]
# Description

Trying to send a CSW 3.0 GetRecords request with an Intersects filter we receive back the following error:

```
ExceptionReport: "Exception: the document is not valid.\n
Error: Element '{http://www.opengis.net/gml/3.2}Envelope':
No matching global element declaration available, but demanded by the strict wildcard. (<string>, line 0)"
```

The filter XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<csw30:GetRecords
    xmlns:csw30="http://www.opengis.net/cat/csw/3.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:gml="http://www.opengis.net/gml"
    outputSchema="http://www.opengis.net/cat/csw/3.0"
    outputFormat="application/xml"
    version="3.0.0"
    service="CSW"
    maxRecords="2"
    xsi:schemaLocation="http://www.opengis.net/cat/csw/3.0
                        http://schemas.opengis.net/cat/csw/3.0/cswAll.xsd
                        http://www.opengis.net/gml
                        http://schemas.opengis.net/gml/3.1.1/gml.xsd">
    <csw30:DistributedSearch hopCount="2" clientId="owslib" distributedSearchId="owslib-request">
        <csw30:federatedCatalogues catalogueURL="https://resource-catalogue.demo.eoepca.org/csw"/>
        <csw30:federatedCatalogues catalogueURL="https://resource-catalogue.mundi.eoepca.org/csw"/>
    </csw30:DistributedSearch>
    <csw30:Query typeNames="csw30:Record">
        <csw30:ElementSetName>summary</csw30:ElementSetName>
        <csw30:Constraint version="2.0.0">
         <fes:Filter>
            <fes:And>
               <fes:PropertyIsEqualTo>
                  <fes:ValueReference>apiso:ParentIdentifier</fes:ValueReference>
                  <fes:Literal>asb:S2MSI1C</fes:Literal>
               </fes:PropertyIsEqualTo>
               <fes:PropertyIsLike escapeChar="\" singleChar="?" wildCard="*">
                  <fes:ValueReference>dc:title</fes:ValueReference>
                  <fes:Literal>S2B*</fes:Literal>
               </fes:PropertyIsLike>
               <fes:PropertyIsEqualTo>
                  <fes:ValueReference>dc:type</fes:ValueReference>
                  <fes:Literal>dataset</fes:Literal>
               </fes:PropertyIsEqualTo>
               <fes:PropertyIsGreaterThanOrEqualTo>
                  <fes:ValueReference>dct:modified</fes:ValueReference>
                  <fes:Literal>2021-05-01</fes:Literal>
               </fes:PropertyIsGreaterThanOrEqualTo>
               <fes:PropertyIsLessThanOrEqualTo>
                  <fes:ValueReference>dct:modified</fes:ValueReference>
                  <fes:Literal>2021-05-02</fes:Literal>
               </fes:PropertyIsLessThanOrEqualTo>
               <fes:Intersects>
                  <fes:ValueReference>ows:BoundingBox</fes:ValueReference>
                  <gml:Envelope>
                     <gml:lowerCorner>14.05 46.46</gml:lowerCorner>
                     <gml:upperCorner>17.24 48.42</gml:upperCorner>
                  </gml:Envelope>
               </fes:Intersects>
            </fes:And>
         </fes:Filter>
        </csw30:Constraint>
    </csw30:Query>
</csw30:GetRecords>
```

# Environment

- operating system: GNU/Linux
- Python version: 3.9
- pycsw version: master
- source/distribution: Docker image `geopython/pycsw:latest`

# Steps to Reproduce

```
import json
from owslib.csw import CatalogueServiceWeb
csw_url = "https://resource-catalogue.demo.eoepca.org/csw"
csw300 = CatalogueServiceWeb(csw_url, version="3.0.0")
query = open('filter.xml', 'rb').read()
csw300.getrecords(xml=query)
```

**Comment by kalxas** [comment]
Also fails with different error when trying with:

```
<?xml version="1.0" encoding="UTF-8"?>
<csw30:GetRecords
    xmlns:csw30="http://www.opengis.net/cat/csw/3.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:gml="http://www.opengis.net/gml/3.2"
    outputSchema="http://www.opengis.net/cat/csw/3.0"
    outputFormat="application/xml"
    version="3.0.0"
    service="CSW"
    maxRecords="2"
    xsi:schemaLocation="http://www.opengis.net/cat/csw/3.0
                        http://schemas.opengis.net/cat/csw/3.0/cswAll.xsd
                        http://www.opengis.net/gml/3.2
                        http://schemas.opengis.net/gml/3.2.1/gml.xsd">
    <csw30:DistributedSearch hopCount="2" clientId="owslib" distributedSearchId="owslib-request">
        <csw30:federatedCatalogues catalogueURL="https://resource-catalogue.demo.eoepca.org/csw"/>
        <csw30:federatedCatalogues catalogueURL="https://resource-catalogue.mundi.eoepca.org/csw"/>
    </csw30:DistributedSearch>
    <csw30:Query typeNames="csw:Record">
        <csw30:ElementSetName>summary</csw30:ElementSetName>
        <csw30:Constraint version="2.0.0">
         <fes:Filter>
            <fes:And>
               <fes:PropertyIsEqualTo>
                  <fes:ValueReference>apiso:ParentIdentifier</fes:ValueReference>
                  <fes:Literal>asb:S2MSI1C</fes:Literal>
               </fes:PropertyIsEqualTo>
               <fes:PropertyIsLike escapeChar="\" singleChar="?" wildCard="*">
                  <fes:ValueReference>dc:title</fes:ValueReference>
                  <fes:Literal>S2B*</fes:Literal>
               </fes:PropertyIsLike>
               <fes:PropertyIsEqualTo>
                  <fes:ValueReference>dc:type</fes:ValueReference>
                  <fes:Literal>dataset</fes:Literal>
               </fes:PropertyIsEqualTo>
               <fes:PropertyIsGreaterThanOrEqualTo>
                  <fes:ValueReference>dct:modified</fes:ValueReference>
                  <fes:Literal>2021-05-01</fes:Literal>
               </fes:PropertyIsGreaterThanOrEqualTo>
               <fes:PropertyIsLessThanOrEqualTo>
                  <fes:ValueReference>dct:modified</fes:ValueReference>
                  <fes:Literal>2021-05-02</fes:Literal>
               </fes:PropertyIsLessThanOrEqualTo>
               <fes:Intersects>
                  <fes:ValueReference>ows:BoundingBox</fes:ValueReference>
                  <gml:Envelope>
                     <gml:lowerCorner>14.05 46.46</gml:lowerCorner>
                     <gml:upperCorner>17.24 48.42</gml:upperCorner>
                  </gml:Envelope>
               </fes:Intersects>
            </fes:And>
         </fes:Filter>
        </csw30:Constraint>
    </csw30:Query>
</csw30:GetRecords>
```

**Comment by tomkralidis** [comment]
The underlying issue is that lxml/libxml2 (used by pycsw) requires a single target for its validating parser.

We see that the CSW 3.0 request above includes **2** physical schema locations.  pycsw uses the CSW schema as the single target, and results in a validation error that cannot find any GML definitions.

The code below exemplifies the issue:

```python
from lxml import etree

schema = 'pycsw/core/schemas/ogc/cat/csw/3.0/cswAll.xsd'
doc = 'file.xml'

xmlschema_doc = etree.parse(schema)
xmlschema = etree.XMLSchema(xmlschema_doc)

doc2 = etree.parse(doc)

xmlschema.assertValid(doc2)
```

Then running results in:

```bash
Traceback (most recent call last):
  File "/test-xml.py", line 12, in <module>
    xmlschema.assertValid(doc2)
  File "src/lxml/etree.pyx", line 3638, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element '{[http://www.opengis.net/gml}Envelope](http://www.opengis.net/gml%7DEnvelope)': No matching global element declaration available, but demanded by the strict wildcard., line 47
```

**Comment by kalxas** [comment]
Works now with:
```
<?xml version="1.0" encoding="UTF-8"?>
<csw30:GetRecords
    xmlns:csw30="http://www.opengis.net/cat/csw/3.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:fes="http://www.opengis.net/fes/2.0"
    xmlns:gml32="http://www.opengis.net/gml/3.2"
    outputSchema="http://www.opengis.net/cat/csw/3.0"
    outputFormat="application/xml"
    version="3.0.0"
    service="CSW"
    maxRecords="2"
    xsi:schemaLocation="http://www.opengis.net/cat/csw/3.0
                        http://schemas.opengis.net/cat/csw/3.0/cswAll.xsd
                        http://www.opengis.net/gml/3.2
                        http://schemas.opengis.net/gml/3.2.1/gml.xsd">
    <csw30:DistributedSearch hopCount="2" clientId="owslib" distributedSearchId="owslib-request">
        <csw30:federatedCatalogues catalogueURL="https://resource-catalogue.demo.eoepca.org/csw"/>
        <csw30:federatedCatalogues catalogueURL="https://resource-catalogue.mundi.eoepca.org/csw"/>
    </csw30:DistributedSearch>
    <csw30:Query typeNames="csw30:Record">
        <csw30:ElementSetName>summary</csw30:ElementSetName>
        <csw30:Constraint version="2.0.0">
         <fes:Filter>
            <fes:And>
               <fes:PropertyIsEqualTo>
                  <fes:ValueReference>apiso:ParentIdentifier</fes:ValueReference>
                  <fes:Literal>asb:S2MSI1C</fes:Literal>
               </fes:PropertyIsEqualTo>
               <fes:PropertyIsLike escapeChar="\" singleChar="?" wildCard="*">
                  <fes:ValueReference>dc:title</fes:ValueReference>
                  <fes:Literal>S2B*</fes:Literal>
               </fes:PropertyIsLike>
               <fes:PropertyIsEqualTo>
                  <fes:ValueReference>dc:type</fes:ValueReference>
                  <fes:Literal>dataset</fes:Literal>
               </fes:PropertyIsEqualTo>
               <fes:PropertyIsGreaterThanOrEqualTo>
                  <fes:ValueReference>dct:modified</fes:ValueReference>
                  <fes:Literal>2021-05-01</fes:Literal>
               </fes:PropertyIsGreaterThanOrEqualTo>
               <fes:PropertyIsLessThanOrEqualTo>
                  <fes:ValueReference>dct:modified</fes:ValueReference>
                  <fes:Literal>2021-05-02</fes:Literal>
               </fes:PropertyIsLessThanOrEqualTo>
               <fes:Intersects>
                  <fes:ValueReference>ows:BoundingBox</fes:ValueReference>
                  <gml32:Envelope>
                     <gml32:lowerCorner>14.05 46.46</gml32:lowerCorner>
                     <gml32:upperCorner>17.24 48.42</gml32:upperCorner>
                  </gml32:Envelope>
               </fes:Intersects>
            </fes:And>
         </fes:Filter>
        </csw30:Constraint>
    </csw30:Query>
</csw30:GetRecords>
```
