### ISSUE TITLE
Clustering Pycsw

### ISSUE THREAD

**Issue by enrico-bellanti** [geopython/pycsw#874]
I'm trying to configure a clustering between two vm with each one with a docker image of pycsw and a external postgres db.
i've have been connected in a master/slave configuration the two db and everything working if i write something in the master it has been replicated in the slave.
The problem is this one that if i start pycsw in the second machine (slave) it starts automatically a series of operation also recreating records table that instead is already replicated in the slave db.
This operation cause a error to trying to write something in only/read db.
My need is to avoid this operation at start up and make the possibility to write in the db slave just when i promote it as master in case of need.
I've been read in the documentation : 
Note: If PostGIS is detected, the pycsw-admin.py script does not create the SFSQL tables as they are already in the
database.

But is not like so.

Has anyone can help me? 
If there is not chance to change this beaviour is there any documentation that explain which is the best way to implement clustering in pycsw between to vm replicated?

that's the error log:

pycsw  |   engine.execute("SELECT version();")
pycsw  | DEBUG:__main__:Database is already up!
pycsw  | INFO:pycsw.core.admin:Creating database postgresql://test:testpassword@10.1.0.73/postgis_db
pycsw  | INFO:pycsw.core.admin:PostGIS 3.3.3 detected: Skipping SFSQL tables creation
pycsw  | INFO:pycsw.core.admin:Creating table records
pycsw  | Traceback (most recent call last):
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
pycsw  |     self.dialect.do_execute(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
pycsw  |     cursor.execute(statement, parameters)
pycsw  | psycopg2.errors.ReadOnlySqlTransaction: cannot execute CREATE TABLE in a read-only transaction
pycsw  |
pycsw  |
pycsw  | The above exception was the direct cause of the following exception:
pycsw  |
pycsw  | Traceback (most recent call last):
pycsw  |   File "/usr/local/bin/entrypoint.py", line 188, in <module>
pycsw  |     launch_pycsw(config, workers=workers, reload=args.reload)
pycsw  |   File "/usr/local/bin/entrypoint.py", line 86, in launch_pycsw
pycsw  |     db_handler(
pycsw  |   File "/usr/local/bin/entrypoint.py", line 135, in handle_postgresql_db
pycsw  |     admin.setup_db(database=database_url, table=table_name,
pycsw  |   File "/home/pycsw/pycsw/pycsw/core/admin.py", line 226, in setup_db
pycsw  |     records.create()
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 962, in create
pycsw  |     bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3233, in _run_ddl_visitor
pycsw  |     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2216, in _run_ddl_visitor
pycsw  |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
pycsw  |     return meth(obj, **kw)
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 899, in visit_table
pycsw  |     self.connection.execute(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
pycsw  |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
pycsw  |     return connection._execute_ddl(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
pycsw  |     ret = self._execute_context(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1948, in _execute_context
pycsw  |     self._handle_dbapi_exception(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2129, in _handle_dbapi_exception
pycsw  |     util.raise_(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
pycsw  |     raise exception
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
pycsw  |     self.dialect.do_execute(
pycsw  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
pycsw  |     cursor.execute(statement, parameters)
pycsw  | sqlalchemy.exc.InternalError: (psycopg2.errors.ReadOnlySqlTransaction) cannot execute CREATE TABLE in a read-only transaction
pycsw  |
pycsw  | [SQL:
pycsw  | CREATE TABLE records (
pycsw  |        identifier TEXT NOT NULL,
pycsw  |        typename TEXT NOT NULL,
pycsw  |        schema TEXT NOT NULL,

**Comment by tomkralidis** [comment]
@enrico-bellanti we can take a look at the Docker entrypoint to handle setting a new repository (or not), or to be able to fail more gracefully.  TBD.

**Comment by tomkralidis** [comment]
Hi @enrico-bellanti, testing pycsw's Docker setup, the entrypoint throws an error if the database/tables already exist, but as a debug statement for logging.  The container continues to connect to a given DB/table as expected and starts accordingly.

I tested this by connecting to the same (PostgreSQL/PostGIS) database/table from multiple containers (3 in the below testing):

```bash
tomkralidis      87015   0.0  0.1 35392220  15384 s000  S+    9:29am   0:00.27 docker run --name pycsw-tom --volume /Users/tomkralidis/Dev/pycsw/pycsw/default.yml:/etc/pycsw/pycsw.yml -p 8001:8000 geopython/pycsw
tomkralidis      88467   0.0  0.1 35408604  18812 s017  S+   10:21am   0:00.05 docker run --name pycsw-tom3 --volume /Users/tomkralidis/Dev/pycsw/pycsw/default.yml:/etc/pycsw/pycsw.yml -p 8003:8000 geopython/pycsw
tomkralidis      88421   0.0  0.1 35391964  15492 s020  S+   10:19am   0:00.05 docker run --name pycsw-tom2 --volume /Users/tomkralidis/Dev/pycsw/pycsw/default.yml:/etc/pycsw/pycsw.yml -p 8002:8000 geopython/pycsw

```
