### ISSUE TITLE
index ix_records_contacts limited?

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pycsw#942]
# Description

when inserting a record,i get this error:

```
ERROR: foo.xml not inserted: (psycopg2.errors.ProgramLimitExceeded) index row size 3896 exceeds btree version 4 maximum 2704 for index "ix_records_contacts"
DETAIL:  Index row references tuple (225,3) in relation "records".
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ProgramLimitExceeded: index row size 3896 exceeds btree version 4 maximum 2704 for index "ix_records_contacts"
DETAIL:  Index row references tuple (225,3) in relation "records".
```

the record has 60 contacts (mainly contributing authors)

# Environment

- operating system: ubuntu/docker
- Python version: 3.8
- pycsw version: master

**Comment by pvgenuchten** [comment]
Got similar on a long abstract today,

Stackoverflow suggested to define index as:

```
create index on the_table(left(the_column(1,100))
```
would that be a solution here?
